export const BIRTHDAY_NAME = "Luiza";

export const FINAL_MESSAGE: string[] = [
  "Luiza,",
  "Cada lembrança que tenho com você é especial e única. Você tem uma presença marcante, uma energia diferente e uma personalidade forte, daquelas que não passam despercebidas. Você tem a capacidade de transformar as pessoas ao seu redor, de despertar o melhor que existe nelas e, comigo, não é diferente. Você sempre me faz querer ser uma pessoa melhor. Saiba o quanto você é especial para mim e, com certeza, para todos aqueles que têm a oportunidade de estar ao seu lado.",
  "Conversar com você sempre foi um acontecimento especial para mim. Mesmo estando distantes, quando conversamos por mensagens, é como se estivéssemos um ao lado do outro, simplesmente conversando sobre tudo e sobre qualquer coisa. É algo que sempre me trouxe, e ainda me traz, uma sensação muito boa.",
  "Eu sei das dificuldades que você enfrenta e, mesmo sabendo que nem sempre é fácil, acredito que você vai conseguir superar cada uma delas. Você é forte, Luiza. Na verdade, é uma das mulheres mais fortes que conheço. Eu tenho fé em você e uma confiança que, para mim, é difícil depositar em alguém.",
  "Por isso, independentemente do que o futuro reserve para mim ou para você, espero sinceramente que você alcance todos os seus objetivos, supere cada obstáculo que surgir no seu caminho e continue seguindo em frente, sempre de cabeça erguida. Você é uma inspiração e alguém por quem tenho uma enorme admiração. Espero, um dia, ter a oportunidade de estar perto e acompanhar você vencendo cada um desses desafios e conquistando tudo aquilo que deseja para a sua vida.",
  "Você sempre foi alguém que me deixou fascinado de uma maneira que poucas pessoas conseguiram. Suas opiniões, sua forma de pensar e a maneira como enxerga o mundo são coisas que admiro muito. Posso dizer, sem exagero, que sou um grande fã de quem você é. E talvez essa seja uma das coisas que mais admiro em você: a sua essência. Nunca deixe de ser essa mulher incrível que você é.",
  "Talvez você até discorde de mim, mas você causa impacto nas pessoas muito mais do que imagina. Torço muito pela sua felicidade. E, por mais incrível que possa parecer, eu rezo todos os dias por você, para que seja feliz, para que tenha forças para enfrentar tudo o que vier pela frente e para que a vida lhe permita conquistar tudo aquilo que seu coração deseja.",
  "Feliz aniversário, Luiza! ❤️ Que seus sonhos se tornem realidade, que você nunca perca essa força que existe dentro de você e que a vida lhe traga muitos motivos para sorrir.",
  "Com carinho, Tassio Medrado",
];
